### ISSUE TITLE
希望增加一个https

### ISSUE THREAD

**Issue by SpectureCarrier** [HoPGoldy/cube-diary#3]
希望能增加https配置，不然公网都不敢开放呀

**Comment by HoPGoldy** [comment]
这个之前也考虑过，不过暂时没有做。比较推荐的是通过前置 nginx 的方式添加 https。

因为 cube 系列的 web app 有好几个，如果每个应用都做的话配置起来比较麻烦。而且这种凭证单独管理比较好。

**Comment by HoPGoldy** [comment]
可以参考 [这里](https://github.com/HoPGoldy/cube-password/blob/master/SECURE.md#1-https-%E7%9B%B8%E5%85%B3) 进行配置
