### ISSUE TITLE
日历列表没有预览， 只有日期

### ISSUE THREAD

**Issue by Aincvy** [HoPGoldy/cube-diary#5]
找了一圈， 没找到设置的地方 

想问 如何打开预览？

**Comment by HoPGoldy** [comment]
预览是指什么？正常情况下编辑完之后返回列表页就能直接看到写好的内容

**Comment by Aincvy** [comment]
![image](https://github.com/HoPGoldy/cube-diary/assets/8110347/ea90c5e2-0885-4cca-ab46-a17e9bb1018d)

![image](https://github.com/HoPGoldy/cube-diary/assets/8110347/2465dd9e-1a71-4013-b8d8-d823d444c0b9)

![image](https://github.com/HoPGoldy/cube-diary/assets/8110347/66acb665-e157-42a4-9995-e4d0efc3266c)

**Comment by HoPGoldy** [comment]
我本地测试了一下，大致是这样的：

- 直接 npm install 到本机并启动（正常）
- 用 docker-compose 初始化并启动（异常）
- 用 docker-compose 初始化后使用本机安装的 cube-diary 运行（正常）

目前能确定如果是 docker-compose 启动的就会导致这个问题，具体原因还在确定。

**Comment by Aincvy** [comment]
npm 或者 node 的版本问题？

**Comment by HoPGoldy** [comment]
应该不是，我昨天测试了 slim，18.18.0，16.20.2，主机运行就可以，但是 docker-compose 启动就都有这个问题

**Comment by HoPGoldy** [comment]
已修复，现在也支持 docker 部署了，可以参考 readme。
